name: Create-NewVersion-And-Draft-Release

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        required: true

jobs:
  Call-Update-Tag:
    uses: ./.github/workflows/UpdateTTTWE.yml
    with:
      tag: ${{ github.event.inputs.tag }}

  Call-Tag2Zip:
    needs: [Call-Update-Tag]
    uses: ./.github/workflows/Tag2Zip.yml
    with:
      tag: ${{ github.event.inputs.tag }}

  Call-ReleaseDraft:
    needs: [Call-Tag2Zip]
    uses: ./.github/workflows/CreateReleaseDraft.yml
    with:
      tag: ${{ github.event.inputs.tag }}

