name: UpdateTTTWE

on:
  workflow_call:
    inputs:
      tag:
        type: string
        required: true
  workflow_dispatch:
    inputs:
      tag:
        type: string
        required: true

jobs:
  Update-TTT-DU:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: replace version
        run: |
          tempjson='makeTempVariable'
          VersionStr=`echo ${{ inputs.tag }} | sed -e "s/^v//"`
          jq ".version|=\"${VersionStr}\"" ./package.json > $tempjson
          mv $tempjson ./package.json

      - name: git commit
        run: |
          git config user.name  "GitHub Action"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add ./package.json
          git commit -m "chore: update TTT-WorldExtension ${{ inputs.tag }}!"
          git tag ${{ inputs.tag }}
          git push
          git push origin ${{ inputs.tag }}
